/**
 * The web app manifest, served at `/manifest.webmanifest` by the production build.
 *
 * ## Why this is a route and not a file
 *
 * It could be `public/manifest.webmanifest`, and it was nearly that. A route is used instead for
 * one reason: the icon list has to name files that exist, and a static file cannot be checked
 * against the filesystem it is served from. As a route, `npm run pwa:test` can import the same
 * object this exports and assert that every path it names is actually in `public/` — so a renamed
 * icon fails a test instead of producing a manifest with a 404 in it.
 *
 * Everything here comes from the application's existing identity. There is no invented brand: the
 * name is the one in `src/app/layout.tsx`, the colours are the two in `globals.css` (`#171717` ink
 * on `#ffffff` paper, with `#f5f5f5` for a surface), and there is no icon font, no splash screen,
 * and no social card.
 *
 * ## What the fields mean for installability
 *
 * Chrome's install criteria are a name, icons at 192 and 512, a `start_url` that resolves, a
 * `display` other than `browser`, and a service worker registered with a fetch handler. The two
 * `any` icons and the maskable one exist to satisfy the first two; `display: "standalone"` and
 * `start_url: "/"` satisfy the next two; `public/sw.js` satisfies the last. Each is verified over
 * HTTP in `npm run pwa:accept`.
 *
 * ## Why there is no `id`, no `scope`, and no `prefer_related_applications`
 *
 * - **`start_url: "/"` rather than a `?source=pwa` marker.** A query string would show up in
 *   SQLite-backed pages as part of the URL and in the browser's history for no benefit; nothing in
 *   this application reads it.
 * - **No `scope`.** The default scope is the directory the manifest is served from, which is `/`.
 *   Writing `"scope": "/"` says the same thing with more text, and an incorrect scope is one of
 *   the easier installability requirements to break.
 * - **No `id`.** It would pin the install identity to a string that cannot change, which is a
 *   decision about how this application is named forever, taken for no gain in V1.
 */
import type { MetadataRoute } from "next";

/**
 * The icon files, generated by `npm run icons` and committed.
 *
 * `purpose` is explicit on each: `any` for the ordinary icon, `maskable` for the one a platform
 * may crop. Declaring both purposes on one file is allowed but then the platform chooses, and a
 * maskable icon that is not actually safe to crop gets cropped anyway — so the maskable file is
 * separate and drawn with its letter inside the safe zone.
 */
const ICONS = [
  { src: "/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
  { src: "/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
  {
    src: "/icon-maskable-512.png",
    sizes: "512x512",
    type: "image/png",
    purpose: "maskable",
  },
] as const;

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Hari OS",
    short_name: "Hari OS",
    description: "A personal operating system that makes daily state visible.",
    // The Dashboard. `/diary` and `/habits` are reachable from it and from the nav, and an app that
    // opened on a photo would be opening on the least important screen.
    start_url: "/",
    display: "standalone",
    // Matches `viewport.themeColor` in `src/app/layout.tsx`. One value in one place would be
    // better; it is duplicated here because the manifest route and the layout export are different
    // modules and this route must not import the layout.
    background_color: "#ffffff",
    theme_color: "#171717",
    icons: [...ICONS],
  };
}
